# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d87532938e45be9b3abf6d36502aa946913c329f6d2ab4e0b428ca32c0034783f221933993fd039e4774b9ebe9cc02ece0b5a708f27fced634f7350132bad9ac

test:
  secret_key_base: 1ae593273406627adac11f61601dda12928444d53175f2f61b750ecd54f7ca29b1206d593b2abd2cc7d11d1efd02e6193be0f0cd0c95afbe7d324ba7b1b19f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
